version: '3.8'

services:
  # Servicio: Django
  django:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: django_twofactor
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    command: python example/manage.py runserver 0.0.0.0:8000

  # Servicio: Jenkins (CI/CD)
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    privileged: true
    restart: unless-stopped

volumes:
  jenkins_data:
